### ISSUE TITLE
Build/install cmxs when possible

### ISSUE THREAD

**Issue by smondet** [solvuu/solvuu-build#26]
Right now the `cmxs` do not seem to be build/installed.

even though `project.mk` mentions them:

```
native: src/coclobas.cmxa src/coclobas_ketrew_backend.cmxa src/coclobas.cmxs src/coclobas_ketrew_backend.cmxs src/app/coclobas.native src/test/coclobas-test.native src/test/coclobas-ketrew.native src/test/coclobas-ketrew-workflow-test.native
```

The ocamlbuild pluging does not build them:

```
$ make src/coclobas.cmxs
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build,nonstd)" src/coclobas.cmxs
Solver failed:
  Ocamlbuild knows of no rules that apply to a target named src/coclobas.cmxs. This can happen if you ask Ocamlbuild to build a target with the wrong extension (e.g. .opt instead of .native) or if the source files live in directories that have not been specified as include directories.
Backtrace:
  - Failed to build the target src/coclobas.cmxs
      - Building src/coclobas.cmxs
make: *** [src/coclobas.cmxs] Error 6
```

(which adds to the strangeness of the `native` make target; it doesn't fail when parts are not done?)

**Comment by agarwal** [comment]
Partially done in 7bf9574b5ad4e40b1a7638b19d406e1cb0309d7d.

However your additional comment about strange `make` behavior holds. If you explicitly request to compile the `cmxs` files, compilation does succeed. However, the opam file only does `make native` which weirdly never builds the `cmxs` files, so an `opam install`fails to install them. I'm investigating.

**Comment by agarwal** [comment]
@smondet This should be working now, but it would be great if you could confirm since I haven't tried to use the generated cmxs files in any project. Note there is now a `build_plugin` argument, which is by default `true`. It can be set to `false` to avoid building `cmxs` files on platforms where it is not supported. It is up to the user to figure out how to determine that since I don't know how.

The generated makefile is also much improved in a601eb57b21418de34ed209bc129fae887386974. The specific issue you mentioned was due to us generating rules like:

```
%.cmxa %.cmxs:
	$(OCAMLBUILD) $@
```

Asking to build `foo.cmxa` and `foo.cmxs` (files with the same base) doesn't cause this rule get invoked once for each file.

**Comment by smondet** [comment]
It seem to be working!

Also the META file is now what one would expect:

```
$ cat /Users/sebastienmondet/.opam/4.02.3+smondet-fix7013/lib/coclobas/META 
directory = ""
version = "master"
archive(byte) = "coclobas.cma"
archive(byte,plugin) = "coclobas.cma"
archive(native) = "coclobas.cmxa"
archive(native,plugin) = "coclobas.cmxs"
requires = "base64 cmdliner cohttp.lwt irmin.git irmin.unix nonstd ppx_deriving.std ppx_deriving_yojson pvem_lwt_unix sosa uuidm"
exists_if = "coclobas.cma"

package "ketrew_backend" (
directory = "ketrew_backend"
version = "master"
archive(byte) = "coclobas_ketrew_backend.cma"
archive(byte,plugin) = "coclobas_ketrew_backend.cma"
archive(native) = "coclobas_ketrew_backend.cmxa"
archive(native,plugin) = "coclobas_ketrew_backend.cmxs"
requires = "base64 cmdliner cohttp.lwt irmin.git irmin.unix ketrew nonstd ppx_deriving.std ppx_deriving_yojson pvem_lwt_unix sosa uuidm coclobas"
exists_if = "coclobas_ketrew_backend.cma"
)
```

**Comment by smondet** [comment]
Thanks!

**Comment by agarwal** [comment]
Great, but beware of #29.
